trigger:
  - main
  
variables:
  tag: '$(Build.BuildId)'
  image: sierrasoftworks/rex

resources:
  repositories:
    - repository: templates
      type: github
      name: SierraSoftworks/devops-pipelines
      endpoint: SierraSoftworks
  
extends:
  template: kubernetes/app.yml@templates
  parameters:
    build:
      - job: build_docker
        displayName: Build Docker Image
        steps:
        - task: Docker@2
          displayName: Build Docker Image
          inputs:
            command: buildAndPush
            dockerfile: 'Dockerfile'
            containerRegistry: Docker Hub
            repository: $(image)
            tags: |
              latest
              $(tag)
    manifests: ./.deploy
    containers: |
      $(image):$(tag)
    staging:
      namespace: rex-staging
      environment: staging-rex-sierrasoftworks-com.rex-staging
      healthcheck: https://staging.rex.sierrasoftworks.com/api/v1/health
    production:
      namespace: rex-prod
      environment: rex-sierrasoftworks-com.rex-prod
      healthcheck: https://rex.sierrasoftworks.com/api/v1/health
